name: evolution-of-todo-phase2
region: nyc

services:
  # Backend - FastAPI Python API
  - name: backend
    github:
      repo: hareemfarooqi2a3/evolution-of-todo
      branch: main
      deploy_on_push: true
    source_dir: phase2_webapp/backend
    dockerfile_path: phase2_webapp/backend/Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    health_check:
      http_path: /
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: BETTER_AUTH_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: DAPR_ENABLED
        scope: RUN_TIME
        value: "false"

  # Frontend - Next.js Web Application
  - name: frontend
    github:
      repo: hareemfarooqi2a3/evolution-of-todo
      branch: main
      deploy_on_push: true
    source_dir: phase2_webapp/frontend
    dockerfile_path: phase2_webapp/frontend/Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    envs:
      - key: NEXT_PUBLIC_API_URL
        scope: RUN_TIME
        value: ${backend.PUBLIC_URL}
